
buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // Plugin Android Gradle
        classpath 'com.android.tools.build:gradle:8.7.0'
        // Plugin Firebase Google Services
        classpath 'com.google.gms:google-services:4.4.2'
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
